### ISSUE TITLE
nopCommerce 4.5 Plugin Not Working

### ISSUE THREAD

**Issue by charlesmatvchuk** [Bungalow64/NOP-Plugin-StyleEditor#7]
The plugin seems to cause css issues and loading issues in nopCommerce 4.5

**Comment by jamie-burns** [comment]
Hey - thanks for raising this.  Do you have any specifics on what the issues are?

**Comment by jamie-burns** [comment]
Ah, just noticed you mentioned 4.5.  I've not had chance to release a 4.5 version of this yet.  I'll use this issue as the placeholder for this next release - I'm not sure when I'll be able to do this, but when I do, I'll update this issue here.

**Comment by jamie-burns** [comment]
@charlesmatvchuk The update for 4.5 has now been published on the nopCommerce marketplace: https://www.nopcommerce.com/en/quick-style-editor-css
